from __future__ import annotations

import json
import os
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "sources.yaml"
OUTPUT = ROOT / "output" / "clash.yaml"
STATUS = ROOT / "output" / "source-status.json"
MAX_NODES = int(os.getenv("MAX_NODES", "500"))
TIMEOUT = int(os.getenv("FETCH_TIMEOUT", "20"))
# Original Clash Premium supports ss/ssr/vmess/socks5/http/snell/trojan.
SKIP_TYPES = {
    "vless",
    "hysteria",
    "hysteria2",
    "tuic",
    "wireguard",
    "ssh",
    "anytls",
    "mieru",
}
# SS2022 and other Meta-only ciphers raise "cipher not supported" on original Clash.
SS_CIPHERS = {
    "aes-128-gcm",
    "aes-192-gcm",
    "aes-256-gcm",
    "chacha20-ietf-poly1305",
    "xchacha20-ietf-poly1305",
    "aes-128-cfb",
    "aes-192-cfb",
    "aes-256-cfb",
    "aes-128-ctr",
    "aes-192-ctr",
    "aes-256-ctr",
    "rc4-md5",
    "chacha20-ietf",
    "xchacha20",
    "chacha20",
    "salsa20",
    "camellia-128-cfb",
    "camellia-192-cfb",
    "camellia-256-cfb",
}
VMESS_CIPHERS = {"auto", "aes-128-gcm", "chacha20-poly1305", "none"}


def fetch(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": "free-vpn-clash-aggregator/1.0"})
    with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
        body = response.read()
    parsed = yaml.safe_load(body) or {}
    if not isinstance(parsed, dict):
        raise ValueError("top-level YAML value is not a mapping")
    return parsed


def fingerprint(proxy: dict) -> tuple:
    fields = ("type", "server", "port", "uuid", "password", "public-key", "private-key", "token")
    return tuple(str(proxy.get(field, "")) for field in fields)


def supported_proxy(proxy: dict) -> bool:
    proxy_type = str(proxy.get("type", "")).strip().lower()
    if proxy_type in SKIP_TYPES:
        return False
    cipher = str(proxy.get("cipher") or "").strip().lower()
    if proxy_type in {"ss", "ssr"}:
        return cipher in SS_CIPHERS
    if proxy_type == "vmess":
        return (cipher or "auto") in VMESS_CIPHERS
    return True


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    config = yaml.safe_load(SOURCES.read_text(encoding="utf-8"))
    entries = config.get("sources", [])
    proxies: list[dict] = []
    seen: set[tuple] = set()
    status = []
    for source in entries:
        name, url = source["name"], source["url"]
        try:
            document = fetch(url)
            candidates = document.get("proxies", [])
            if not isinstance(candidates, list):
                raise ValueError("proxies is not a list")
            added = 0
            for proxy in candidates:
                if not isinstance(proxy, dict) or not proxy.get("name") or not proxy.get("type"):
                    continue
                if not supported_proxy(proxy):
                    continue
                key = fingerprint(proxy)
                if key in seen:
                    continue
                seen.add(key)
                proxy = dict(proxy)
                base_name = str(proxy["name"]).strip()[:80]
                used_names = {item["name"] for item in proxies}
                candidate_name = base_name
                suffix = 2
                while candidate_name in used_names:
                    candidate_name = f"{base_name} #{suffix}"
                    suffix += 1
                proxy["name"] = candidate_name
                proxies.append(proxy)
                added += 1
            status.append({"name": name, "url": url, "ok": True, "received": len(candidates), "added": added})
        except Exception as exc:  # one broken upstream must not block the other sources
            status.append({"name": name, "url": url, "ok": False, "error": str(exc)})

    if not proxies:
        raise RuntimeError("all upstream sources failed or returned no Clash proxies")

    proxies = proxies[:MAX_NODES]
    names = [proxy["name"] for proxy in proxies]
    generated = {
        "mixed-port": 7890,
        "allow-lan": False,
        "mode": "rule",
        "log-level": "info",
        "proxies": proxies,
        "proxy-groups": [
            {"name": "AUTO", "type": "url-test", "url": "http://www.gstatic.com/generate_204", "interval": 300, "tolerance": 50, "proxies": names},
            {"name": "PROXY", "type": "select", "proxies": ["AUTO", "DIRECT"] + names},
        ],
        "rules": ["MATCH,PROXY"],
    }
    OUTPUT.write_text("# Generated by scripts/update.py; do not edit.\n" + yaml.safe_dump(generated, allow_unicode=True, sort_keys=False), encoding="utf-8")
    STATUS.write_text(json.dumps({"generated_at": datetime.now(timezone.utc).isoformat(), "proxy_count": len(proxies), "sources": status}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"proxy_count": len(proxies), "sources": status}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
